
database:
  engine: "mysql+pymysql"
  path: "rag.db"
  host: "localhost"
  port: 3306
  username: "yifei"
  password: "111111"
  mydb: "yeefeirag"

milvus:
  dims: 768
  host: "localhost"
  port: 19530

deviceSettings:
  device: "cpu"


models:
  embedding_model:
    bge-small-zh-v1.5:
      hf_url: "https://huggingface.co/BAAI/bge-small-zh-v1.5"
      local_url: "./models/BAAI/bge-small-zh-v1.5/"
      dims: 512

  rerank_model:
    bge-reranker-base:
      hf_url: "https://huggingface.co/BAAI/bge-reranker-base"
      local_url: "./models/BAAI/bge-reranker-base"


rag:
  llm_base: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  llm_api_key: "sk-cbf8dce472b74ddfbf3210f7d52dd758"
  #llm_model: "qwen-plus"

  vllm_base: "http://localhost:8000/v1"
  vllm_api_key: "43aa6570992d01fab078e157e07b4f52.ocKHwNGxhIBrDZD4"
  #vllm_model: "models/Qwen/Qwen3.5-0.8B/"
  temperature: 0.1
  model: "qwen-plus"

  embedding_model: "bge-small-zh-v1.5"
  rerank_model: "bge-reranker-base"
  chunk_size: 256
  chunk_overlap: 20
  chunk_candidate: 10
  use_embedding: true
  use_rerank: false
  use_rrf: true
  port: 6010
  provider: "openai"

# 多轮对话配置
multi_dialogue_rag:
  estimate_token_fun: avg  # 默认token估计方式
  llm_max_token: 1024  # 大模型最长token数量
  cut_dialogue_scale: 2   # 预估达到最长token时的裁切比例，2表时裁切一半的历史对话生成摘要
  max_token_threshold: 1.01   # 最长token的缓冲值 > 1 表示宽松策略，<1 表示严格策略
  smith_debug: false  # 是否使用 Langsmith 进行debug查看
  console_debug: true  # 是否启用控制台日志查看
  thinking_in_context: false  # 是否将思考内容加入上下文历史对话