
database:
  engine: "mysql+pymysql"
  path: "rag.db"
  host: "localhost"
  port: 3306
  username: "yifei"
  password: "111111"
  mydb: "yeefeirag"

milvus:
  dims: 768,
  host: "localhost"
  port: 3306

device: "cpu" # "cpu"


models:
  embedding_model:
    bge-small-zh-v1.5:
      hf_url: "https://huggingface.co/BAAI/bge-small-zh-v1.5"
      local_url: "../models/BAAI/bge-small-zh-v1.5/"
      dims: 512

  rerank_model:
    bge-reranker-base:
      hf_url: "https://huggingface.co/BAAI/bge-reranker-base"
      local_url: ""


rag:
  llm_base: "http://localhost:8000/v1"
  llm_api_key: "43aa6570992d01fab078e157e07b4f52.ocKHwNGxhIBrDZD4"
  llm_model: "models/Qwen/Qwen3.5-0.8B/"
  embedding_model: "bge-small-zh-v1.5"
  rerank_model: "bge-reranker-base"
  chunk_size: 256
  chunk_overlap: 20
  chunk_candidate: 10
  use_embedding: true
  use_rerank: false
  use_rrf: true
  port: 6010
